import { themeOf, type ThemeId } from '../shared/themes'
import type { TableSet } from '../shared/types'
import gothic from './defaults.en.json'
import themed from './themed.en.json'

// The table sets the tool ships with, one for each theme. Both files are
// generated by scripts/build-defaults.py.

const all = [gothic, ...themed] as TableSet[]

/** The Hellenic set first: it is the one open on a first visit. */
export const DEFAULT_SETS = [...all.filter((s) => s.theme === 'hellenic'), ...all.filter((s) => s.theme !== 'hellenic')]

/** The default set of a theme. */
export function defaultFor(theme: ThemeId): TableSet {
  return DEFAULT_SETS.find((s) => themeOf(s) === theme) ?? DEFAULT_SETS[0]
}
